name: Build and Deploy GTFS importer

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - submitted
      - closed
  workflow_dispatch:

env:
  ConnectionStrings__AppDbConnectionString: Server=myServerAddress;Database=myDataBase;Uid=myUsername;Pwd=myPassword;
  DB_SERVER_VERSION: 8.0.43

jobs:
  build-and-push:
    name: Build and push ⛏
    runs-on: ubuntu-22.04-arm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish
        run: dotnet publish ./Tools/GtfsImporter/GtfsImporter.csproj --ucr --artifacts-path artifacts --nologo --self-contained

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build Docker image
        run: |
          docker build --platform arm64 -t ${{ secrets.DOCKER_USERNAME }}/wspolny-dojazd:gtfs-importer ./Tools/GtfsImporter

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/wspolny-dojazd:gtfs-importer
