name: Run tests

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize, ready_for_review]

concurrency:
  group: tests-${{ github.head_ref }}
  cancel-in-progress: true

env:
  ConnectionStrings__AppDbConnectionString: Server=myServerAddress;Database=myDataBase;Uid=myUsername;Pwd=myPassword;
  DB_SERVER_VERSION: 8.0.43

jobs:
  build:
    name: Run tests
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install EF tooling
        run: dotnet tool install --global dotnet-ef

      - name: Restore dependencies
        run: dotnet restore Backend.sln --ucr

      - name: Build
        run: dotnet build --ucr -c Release --no-restore

      - name: Testing
        run: dotnet test --no-build --no-restore
